import { NavBar } from "@components/NavBar/NavBar";
import { FontKumbhSans, FontMontserrat } from "@lib/fonts";
import "@styles/globals.css";
import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <div className="fixed w-full top-0 z-50">
        <NavBar />
      </div>
      <body className={`${FontMontserrat.variable} ${FontKumbhSans.variable}`}>{children}</body>
    </html>
  );
}
